### ISSUE TITLE
Auto-threshold mask

### ISSUE THREAD

**Issue by Epta13** [guiwitz/napari-sediment#11]
I am (today) getting this error on the Auto Threshold mask tool:
ValueError: Arrays chunk sizes are unknown: (nan,)v

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~\.conda\envs\sediment\lib\site-packages\napari_sediment\sediment_widget.py:946, in SedimentWidget._on_click_automated_threshold(self=<napari_sediment.sediment_widget.SedimentWidget object>)
    944 else:
    945     pix_selected = np.ravel(im)
--> 946 med_val, std_val = fit_1dgaussian_without_outliers(data=pix_selected[::5])
        pix_selected = dask.array<getitem, shape=(nan,), dtype=float64, chunksize=(nan,), chunktype=numpy.ndarray>
    947 #self.slider_mask_threshold.setRange(im.min(), im.max())
    948 fact = self.spin_automated_mask_width.value()

File ~\.conda\envs\sediment\lib\site-packages\dask\array\core.py:1994, in Array.__getitem__(self=dask.array<getitem, shape=(nan,), dtype=float64, chunksize=(nan,), chunktype=numpy.ndarray>, index=(slice(None, None, 5),))
   1991     return self
   1993 out = "getitem-" + tokenize(self, index2)
-> 1994 dsk, chunks = slice_array(out, self.name, self.chunks, index2, self.itemsize)
        index2 = (slice(None, None, 5),)
        out = 'getitem-5211831b47b8d2819fd691a2b140fbbf'
        self = dask.array<getitem, shape=(nan,), dtype=float64, chunksize=(nan,), chunktype=numpy.ndarray>
   1996 graph = HighLevelGraph.from_collections(out, dsk, dependencies=[self])
   1998 meta = meta_from_array(self._meta, ndim=len(chunks))

File ~\.conda\envs\sediment\lib\site-packages\dask\array\slicing.py:176, in slice_array(out_name='getitem-5211831b47b8d2819fd691a2b140fbbf', in_name='getitem-90f2b7da9ce74f60a62af21d083fffed', blockdims=((nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, ...),), index=(slice(None, None, 5),), itemsize=8)
    173 index += (slice(None, None, None),) * missing
    175 # Pass down to next function
--> 176 dsk_out, bd_out = slice_with_newaxes(out_name, in_name, blockdims, index, itemsize)
        blockdims = ((nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan),)
        index = (slice(None, None, 5),)
        out_name = 'getitem-5211831b47b8d2819fd691a2b140fbbf'
        in_name = 'getitem-90f2b7da9ce74f60a62af21d083fffed'
        itemsize = 8
    178 bd_out = tuple(map(tuple, bd_out))
    179 return dsk_out, bd_out

File ~\.conda\envs\sediment\lib\site-packages\dask\array\slicing.py:198, in slice_with_newaxes(out_name='getitem-5211831b47b8d2819fd691a2b140fbbf', in_name='getitem-90f2b7da9ce74f60a62af21d083fffed', blockdims=((nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, ...),), index=(slice(None, None, 5),), itemsize=8)
    195         where_none[i] -= n
    197 # Pass down and do work
--> 198 dsk, blockdims2 = slice_wrap_lists(out_name, in_name, blockdims, index2, itemsize)
        index2 = (slice(None, None, 5),)
        out_name = 'getitem-5211831b47b8d2819fd691a2b140fbbf'
        in_name = 'getitem-90f2b7da9ce74f60a62af21d083fffed'
        blockdims = ((nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan),)
        itemsize = 8
    200 if where_none:
    201     expand = expander(where_none)

File ~\.conda\envs\sediment\lib\site-packages\dask\array\slicing.py:254, in slice_wrap_lists(out_name='getitem-5211831b47b8d2819fd691a2b140fbbf', in_name='getitem-90f2b7da9ce74f60a62af21d083fffed', blockdims=((nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, ...),), index=(slice(None, None, 5),), itemsize=8)
    252 # No lists, hooray! just use slice_slices_and_integers
    253 if not where_list:
--> 254     return slice_slices_and_integers(out_name, in_name, blockdims, index)
        index = (slice(None, None, 5),)
        out_name = 'getitem-5211831b47b8d2819fd691a2b140fbbf'
        in_name = 'getitem-90f2b7da9ce74f60a62af21d083fffed'
        blockdims = ((nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan),)
    256 # Replace all lists with full slices  [3, 1, 0] -> slice(None, None, None)
    257 index_without_list = tuple(
    258     slice(None, None, None) if is_arraylike(i) else i for i in index
    259 )

File ~\.conda\envs\sediment\lib\site-packages\dask\array\slicing.py:303, in slice_slices_and_integers(out_name='getitem-5211831b47b8d2819fd691a2b140fbbf', in_name='getitem-90f2b7da9ce74f60a62af21d083fffed', blockdims=((nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, ...),), index=(slice(None, None, 5),))
    301 for dim, ind in zip(shape, index):
    302     if np.isnan(dim) and ind != slice(None, None, None):
--> 303         raise ValueError(
    304             f"Arrays chunk sizes are unknown: {shape}{unknown_chunk_message}"
    305         )
    307 assert all(isinstance(ind, (slice, Integral)) for ind in index)
    308 assert len(index) == len(blockdims)

ValueError: Arrays chunk sizes are unknown: (nan,)

A possible solution: https://docs.dask.org/en/latest/array-chunks.html#unknown-chunks
Summary: to compute chunks sizes, use

   x.compute_chunk_sizes()  # for Dask Array `x`
   ddf.to_dask_array(lengths=True)  # for Dask DataFrame `ddf`

**Comment by guiwitz** [comment]
This was a bug. Should be fixed in [4b1f07d](https://github.com/guiwitz/napari-sediment/commit/4b1f07da9fca0819e2cc091d54078749a0172ab0)
