### ISSUE TITLE
Reduce on eigenvalues

### ISSUE THREAD

**Issue by Epta13** [guiwitz/napari-sediment#14]
This function does not work:

---------------------------------------------------------------------------
AxisError                                 Traceback (most recent call last)
File ~\.conda\envs\sediment\lib\site-packages\napari_sediment\hyperanalysis_widget.py:428, in HyperAnalysisWidget._on_click_reduce_mnfr_on_eigen(self=<napari_sediment.hyperanalysis_widget.HyperAnalysisWidget object>)
    426 self.selected_bands = self.image_mnfr[:,:, last_index].copy()
    427 if 'denoised' in self.viewer.layers:
--> 428     self.viewer.layers['denoised'].data = np.moveaxis(self.selected_bands, 2, 0)
        self.selected_bands = <class 'numpy.ndarray'> (1370, 60) float64
        self = <napari_sediment.hyperanalysis_widget.HyperAnalysisWidget object at 0x00000258DE477550>
        self.viewer = Viewer(camera=Camera(center=(0.0, 774.0048231720485, -49.69838202125902), zoom=0.565639111250939, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(0.0, 1763.151338324631, 1201.0991212716744), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=3, ndisplay=2, last_used=0, range=((0.0, 392.0, 1.0), (0.0, 1370.0, 1.0), (0.0, 60.0, 1.0)), current_step=(0, 684, 29), order=(0, 1, 2), axis_labels=('0', '1', '2')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Image layer 'imcube' at 0x258eae3f730>, <Labels layer 'mask' at 0x258eabc62b0>, <Image layer 'mnfr' at 0x258e901d0a0>, <Image layer 'denoised' at 0x258e8d20490>], help='use <2> for transform', status={'layer_base': 'imcube', 'source_type': '', 'plugin': '', 'coordinates': ' [0 1763 1201]'}, tooltip=Tooltip(visible=True, text=''), theme='dark', title='napari', mouse_over_canvas=True, mouse_move_callbacks=[<bound method HyperAnalysisWidget._shift_move_callback of <napari_sediment.hyperanalysis_widget.HyperAnalysisWidget object at 0x00000258DE477550>>], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x00000258D1228AF0>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={})
        np.moveaxis = <function moveaxis at 0x00000258C8C57F70>
        np = <module 'numpy' from 'C:\\Users\\pzahajska\\.conda\\envs\\sediment\\lib\\site-packages\\numpy\\__init__.py'>
    429 else:
    430     self.viewer.add_image(np.moveaxis(self.selected_bands, 2, 0), name='denoised', rgb=False)

File ~\.conda\envs\sediment\lib\site-packages\numpy\core\numeric.py:1449, in moveaxis(a=<class 'numpy.ndarray'> (1370, 60) float64, source=2, destination=0)
   1446     a = asarray(a)
   1447     transpose = a.transpose
-> 1449 source = normalize_axis_tuple(source, a.ndim, 'source')
        source = 2
        a = <class 'numpy.ndarray'> (1370, 60) float64
   1450 destination = normalize_axis_tuple(destination, a.ndim, 'destination')
   1451 if len(source) != len(destination):

File ~\.conda\envs\sediment\lib\site-packages\numpy\core\numeric.py:1380, in normalize_axis_tuple(axis=[2], ndim=2, argname='source', allow_duplicate=False)
   1378         pass
   1379 # Going via an iterator directly is slower than via list comprehension.
-> 1380 axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
        axis = [2]
        argname = 'source'
        ndim = 2
   1381 if not allow_duplicate and len(set(axis)) != len(axis):
   1382     if argname:

File ~\.conda\envs\sediment\lib\site-packages\numpy\core\numeric.py:1380, in <listcomp>(.0=<list_iterator object>)
   1378         pass
   1379 # Going via an iterator directly is slower than via list comprehension.
-> 1380 axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
        argname = 'source'
        ax = 2
        ndim = 2
   1381 if not allow_duplicate and len(set(axis)) != len(axis):
   1382     if argname:

AxisError: source: axis 2 is out of bounds for array of dimension 2

**Comment by guiwitz** [comment]
Fixed by [9dedb3b](https://github.com/guiwitz/napari-sediment/commit/9dedb3be7250e4e23949efa5b5fd292740bfbb85)
