### ISSUE TITLE
HyperAnalysis End Members

### ISSUE THREAD

**Issue by Epta13** [guiwitz/napari-sediment#17]
In the end member tab, would it be possible to have the oprion of curve smoothing (similar to the plotting tool in the Sediment plugin) and also the option to choose between the continuum removed and the not-continuum removed displaying of data?

**Comment by guiwitz** [comment]
Should now be available via [7f2e422](https://github.com/guiwitz/napari-sediment/commit/7f2e4224f2efd13df5c4e93e819d235011136f74).
