### ISSUE TITLE
Mask/Auto: Intensity distribution width

### ISSUE THREAD

**Issue by aloboa** [guiwitz/napari-sediment#20]
What is Intensity distribution width in Mask/Auto ?

**Comment by guiwitz** [comment]
I added some explanations [here](https://guiwitz.github.io/napari-sediment/Details_sediment.html#auto-threshold). That info is now also directly accessible from the interface via [451af74](https://github.com/guiwitz/napari-sediment/commit/451af7429d54b877497b9ef752bff46c6b6c2525).
