### ISSUE TITLE
File names

### ISSUE THREAD

**Issue by Epta13** [guiwitz/napari-sediment#31]
I know this is silly, but we still have people using . in the file names. Napari cannot deal with it at this point.

I tested the batch processing, and it got stuck on the files/folders with a period (.) in the names.
Can we do something about this, or do we just need to teach users to name files and folders computer-friendly?

![Screenshot 2024-04-15 at 11 59 14](https://github.com/guiwitz/napari-sediment/assets/91525516/89b91b28-7769-4ed4-90b8-3d02c5c4a7ae)

**Comment by Epta13** [comment]
Today I managed to run the batch pre-processing with files names including . in the name. So this issue might have another reason.

**Comment by guiwitz** [comment]
Closing for the moment, as this seems solved.
