### ISSUE TITLE
Manual Mask Thershold

### ISSUE THREAD

**Issue by Epta13** [guiwitz/napari-sediment#32]
Would it be possible:
1. type in the values, just above the slider
2. remember the previous values if the masking is done several times? Now the slider goes back to the full extend.

**Comment by guiwitz** [comment]
For 1. the values are already editable (not the left and right numbers which are the limits, but the one on top of the slider). For 2. this should be solved by 3f9b18bbfb2f6c27f5817784a458f19639b985cf
