### ISSUE TITLE
Spectral end-members plot axes

### ISSUE THREAD

**Issue by Epta13** [guiwitz/napari-sediment#40]
The end-member plot in the SpectralIndices plugin is saved with white axes ticks and has no axes labels.
We need to improve this because the axes are not visible on the white background, and the labels of the axes need to be added everywhere in the workflow.

Also, could we have the spectra-color bar below the wavelength axis? Similarly to this:
![Screenshot 2024-05-21 at 10 22 53](https://github.com/guiwitz/napari-sediment/assets/91525516/6e163384-1736-4aad-a485-d17d0ce312ec)

**Comment by guiwitz** [comment]
This should now be taken care of in [cc2db76](https://github.com/guiwitz/napari-sediment/commit/cc2db76995c4aed8656dd5eaba79e2e372f76cdf)

**Comment by guiwitz** [comment]
Colorbar is taken care by 3c09325. Closing this for now but fee free to re-open if necessary.
