### ISSUE TITLE
Cannot save the corrected data

### ISSUE THREAD

**Issue by Epta13** [guiwitz/napari-sediment#5]
In the first module - Sediment, tab Processing, Correct and save data. This operation gives an error: 'SedimentWidget' object has no attribute 'spin_chunksize'. The operation is not executed.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~\.conda\envs\sediment\lib\site-packages\napari_sediment\sediment_widget.py:878, in SedimentWidget._on_click_batch_correct(self=<napari_sediment.sediment_widget.SedimentWidget object>)
    864 with progress(total=0) as pbr:
    865     pbr.set_description("Preprocessing full image")
    867     correct_save_to_zarr(
    868         imhdr_path=self.imhdr_path,
    869         white_file_path=self.white_file_path,
    870         dark_for_im_file_path=self.dark_for_im_file_path,
    871         dark_for_white_file_path=self.dark_for_white_file_path,
    872         zarr_path=self.export_folder.joinpath('corrected.zarr'),
    873         band_indices=None,
    874         min_max_bands=min_max_band,
    875         background_correction=self.check_batch_white.isChecked(),
    876         destripe=self.check_batch_destripe.isChecked(),
    877         use_dask=self.check_use_dask.isChecked(),
--> 878         chunk_size=self.spin_chunksize.value()
        self = <napari_sediment.sediment_widget.SedimentWidget object at 0x000001BD61186550>
        self.imhdr_path = WindowsPath('F:/HSI/Bremen/U-channel/slides_ArabianSea_240207-114854/capture/slides_ArabianSea_240207-114854.hdr')
        self.white_file_path = WindowsPath('F:/HSI/Bremen/U-channel/slides_ArabianSea_WR_240207-115838/capture/WHITEREF_slides_ArabianSea_WR_240207-115838.hdr')
        self.dark_for_im_file_path = WindowsPath('F:/HSI/Bremen/U-channel/slides_ArabianSea_240207-114854/capture/DARKREF_slides_ArabianSea_240207-114854.hdr')
        self.dark_for_white_file_path = WindowsPath('F:/HSI/Bremen/U-channel/slides_ArabianSea_WR_240207-115838/capture/DARKREF_slides_ArabianSea_WR_240207-115838.hdr')
        self.export_folder = WindowsPath('F:/HSI/Bremen/U-channel/Napari/Arabian_sea_slides')
        min_max_band = [396.0, 1007.0]
        self.check_batch_white = <PyQt5.QtWidgets.QCheckBox object at 0x000001BD66D9CF70>
        self.check_batch_destripe = <PyQt5.QtWidgets.QCheckBox object at 0x000001BD66D96040>
        self.check_use_dask = <PyQt5.QtWidgets.QCheckBox object at 0x000001BD66D96430>
    879         )
    881 self.viewer.window._status_bar._toggle_activity_dock(False)

AttributeError: 'SedimentWidget' object has no attribute 'spin_chunksize'

**Comment by guiwitz** [comment]
This was a bug as the variable was misspelled. Should be fixed by [0cfec9a](https://github.com/guiwitz/napari-sediment/commit/0cfec9ae86ea933cfb52907806eaf699bd59aace). Please just pip install again.
