### ISSUE TITLE
Mask tools

### ISSUE THREAD

**Issue by Epta13** [guiwitz/napari-sediment#6]
- Would it be possible to add an option to remove the mask from the mask layer in the manual and auto threshold masking tab, so I don't have to delete the whole mask layer? In the other tabs/options, it always create a new mask layer, so this is easy to remove if I don't like the mask. But in the Manual and auto threshold masking tool, this is not an option.

- Further, the ML training on imcube and mainly the segmentation of image takes bloody ages on Windows (W11, RAM 32GB, 3.2Ghz, 6cores) and makes the PC impossible to work on. Maybe this would be resolved by running it in Renku?

- Plus, I cannot see the result of the model training in the segmentation layer before I do the image segmentation, which takes like 10mins.

**Comment by guiwitz** [comment]
- If I correctly understand, you would like the manual/threshold options to generate separate layers e.g. ```mask_manual``` and ```mask_threshold```? I can implement that.
- For the ML training: these images are huge so it's better to use the ```Downsample``` option and to set it to 2 or 4. This generates a slightly coarser masks but goes way faster.

**Comment by Epta13** [comment]
- Yes, a separate masks layers would solve this. 

- Okej, I will try. I am now working on only 25cm with width of 4cm, so I can imgine that for a core it will take veeery long without downsampling.

- Bassically yes, because if I can'r see the result of the model without segmentation, there is no need to have this separately, right? Or if I can see the "mask" (0-1) before applying to the data, that would be sufficient. The segmentation is the appication of the model in the imcube, right?

**Comment by guiwitz** [comment]
These points should be fixed now:
- To avoid confusion, the ```mask``` layer is now called ```manual-mask``` and is the layer where one can manually draw annotations.
- The two threshold-based masks called (from the Manual and Auto tabs) generate an ```intensity-mask``` (there's no reason to separate the two as they both use the intensities set by the sliders, once set manually, once automatically).
- In the ML tab, the training button is now called Training + Segmentation and automatically generates segmentation after training

**Comment by Epta13** [comment]
Perfect, thanks, I will take notes of this in my "manual" which thenb can be added to the documentation page.

The border mask is not really working on my short dataset. It makes only a thin line on the edge. I guess this is then causing the ROIs being a wierdshaped.?

![Screenshot 2024-02-14 105556](https://github.com/guiwitz/napari-sediment/assets/91525516/1934ccdd-6c70-45c5-8625-0577ea0158be)

![Screenshot 2024-02-14 105615](https://github.com/guiwitz/napari-sediment/assets/91525516/6ee69d29-7aed-42be-9e9c-c7b8d08395db)

**Comment by guiwitz** [comment]
Yes, the border mask is quite "fragile". It's meant to remove obvious "uninteresting" regions, but it might not always work. Now I'm wondering if I shouldn't remove this in favour of something where you can indicate left/right, top/bottom margins to exclude?

**Comment by Epta13** [comment]
Well, for most of the cores it works nicely. It's only some of the more specific scanse, like slides, where it doesn't work that well. But yes, defining the margins would be also a way how to deal with this.

**Comment by Epta13** [comment]
All was solved. Some notes can be use in the documentation.
