### ISSUE TITLE
Batch preprocessing plugin does not open

### ISSUE THREAD

**Issue by Epta13** [guiwitz/napari-sediment#67]
I can't open the batch preprocessing plugin:

Failed to import command at 'napari_sediment.batch_preproc:BatchPreprocWidget': module 'napari_sediment.batch_preproc' has no attribute 'BatchPreprocWidget'

The batch preprocessing in the Sediment plugin works though.

**Comment by guiwitz** [comment]
Should be fixed with 43fd64e
