### ISSUE TITLE
Sediment - Metadata - pixels size computation

### ISSUE THREAD

**Issue by Epta13** [guiwitz/napari-sediment#68]
It seems that the automated pixel size computation does not work. I have added the scale layer, filled in the scale size units (total real length of the scale bar) and when I press compute pixel size, nothing happens in the metadate part. The pixel size does not update. Is this correct or it doesn't work?

**Comment by guiwitz** [comment]
Values of pixel sizes smaller than 1 were not allowed. This bug should be fixed via a0c5483

**Comment by Epta13** [comment]
Yes, now it works. Only one thing. I would liek to have the units of the scale bar in cm, and that means that the pixel size will be very small number. But now it allows only ofr 0.01 as the smallest. Could you add more decimals, so it allows to show the pixel size in cm, e.g. 0.00577cm is the pixel size of my 99cm core. I want to have the final core scale at the plto as mm or cm.
