### ISSUE TITLE
ML masking error: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by Epta13** [guiwitz/napari-sediment#79]
When running the ML masking in the newest version of napari-sediment, installed from napari, this error appears:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: 'NoneType' object is not callable

The result is that it doesn't save the output of the first plugin correctly, and thus, the HyperAnalysis plugin is not able to open the imcube, nor RGB. It opens only an empty mask.
Further, when the exported files from Sediment plugin are reopened in the Sediment plugin, the mask is shifted comapred to the RGB and imcube.

**Comment by Epta13** [comment]
If I don't use ML masking, this error does not appear.

**Comment by Epta13** [comment]
This error appears during the ML training. The training will finish, and the segmentation will finish and give good results, but when I want to then combine masks or export the project, it won't let me and this error appears from the training on. Even if I just hover over the ML panel with coursor, over the pixel classifier panel, this error appear instantly.

**Comment by guiwitz** [comment]
This was a bug in napari-convpaint. It has been fixed now in https://github.com/guiwitz/napari-convpaint/commit/da1d2e5acc6f0e13402a47b4042d7a9264ec3379. Making sure that napari-convpaint 0.5.2 is installed should solve the problem.
