### ISSUE TITLE
Load project in HyperAnalysis module

### ISSUE THREAD

**Issue by Epta13** [guiwitz/napari-sediment#9]
The loading of project in the HyperAnalysis doesn't work:
I get this error with loading the exported .zarr
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~\.conda\envs\sediment\lib\site-packages\napari_sediment\hyperanalysis_widget.py:238, in HyperAnalysisWidget.import_project(self=<napari_sediment.hyperanalysis_widget.HyperAnalysisWidget object>)
    235 self.row_bounds = [self.rois[0][:,0].min(), self.rois[0][:,0].max()]
    236 self.col_bounds = [self.rois[0][:,1].min(), self.rois[0][:,1].max()]
--> 238 self._on_click_load_mask()
        self = <napari_sediment.hyperanalysis_widget.HyperAnalysisWidget object at 0x000001B045B77550>
    240 if self.check_load_corrected.isChecked():
    241     self.imagechannels = ImChannels(self.export_folder.joinpath('corrected.zarr'))

File ~\.conda\envs\sediment\lib\site-packages\napari_sediment\hyperanalysis_widget.py:370, in HyperAnalysisWidget._on_click_load_mask(self=<napari_sediment.hyperanalysis_widget.HyperAnalysisWidget object>)
    368     self.viewer.layers['mask'].data = mask
    369 else:
--> 370     self.viewer.add_labels(mask, name='mask')
        mask = <class 'numpy.ndarray'> (2, 0, 1312) uint8
        self.viewer = Viewer(camera=Camera(center=(0.0, 0.0, 0.0), zoom=1.0, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(1.0, 1.0), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=2, ndisplay=2, last_used=0, range=((0, 2, 1), (0, 2, 1)), current_step=(0, 0), order=(0, 1), axis_labels=('0', '1')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[], help='', status='Ready', tooltip=Tooltip(visible=True, text=''), theme='dark', title='napari', mouse_over_canvas=True, mouse_move_callbacks=[<bound method HyperAnalysisWidget._shift_move_callback of <napari_sediment.hyperanalysis_widget.HyperAnalysisWidget object at 0x000001B045B77550>>], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x000001B038CBFAF0>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={})
        self = <napari_sediment.hyperanalysis_widget.HyperAnalysisWidget object at 0x000001B045B77550>

File ~\.conda\envs\sediment\lib\site-packages\napari\utils\_proxies.py:188, in CallablePublicOnlyProxy.__call__(self=<bound method add_labels of Viewer(camera=Camera...use_drag_gen={}, _mouse_wheel_gen={}, keymap={})>, *args=[<class 'numpy.ndarray'> (2, 0, 1312) uint8], **kwargs={'name': 'mask'})
    180 args = [
    181     arg.__wrapped__ if isinstance(arg, PublicOnlyProxy) else arg
    182     for arg in args
    183 ]
    184 kwargs = {
    185     k: v.__wrapped__ if isinstance(v, PublicOnlyProxy) else v
    186     for k, v in kwargs.items()
    187 }
--> 188 return self.create(self.__wrapped__(*args, **kwargs))
        args = [<class 'numpy.ndarray'> (2, 0, 1312) uint8]
        kwargs = {'name': 'mask'}
        self = <bound method add_labels of Viewer(camera=Camera(center=(0.0, 0.0, 0.0), zoom=1.0, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(1.0, 1.0), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=2, ndisplay=2, last_used=0, range=((0, 2, 1), (0, 2, 1)), current_step=(0, 0), order=(0, 1), axis_labels=('0', '1')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[], help='', status='Ready', tooltip=Tooltip(visible=True, text=''), theme='dark', title='napari', mouse_over_canvas=True, mouse_move_callbacks=[<bound method HyperAnalysisWidget._shift_move_callback of <napari_sediment.hyperanalysis_widget.HyperAnalysisWidget object at 0x000001B045B77550>>], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x000001B038CBFAF0>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={})>

File ~\.conda\envs\sediment\lib\site-packages\napari\components\viewer_model.py:4, in add_labels(self=Viewer(camera=Camera(center=(0.0, 0.0, 0.0), zoo...ouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}), data=<class 'numpy.ndarray'> (2, 0, 1312) uint8, num_colors=50, features=None, properties=None, color=None, seed=0.5, name='mask', metadata=None, scale=None, translate=None, rotate=None, shear=None, affine=None, opacity=0.7, blending='translucent', rendering='iso_categorical', depiction='volume', visible=True, multiscale=None, cache=True, plane=None, experimental_clipping_planes=None)
      1 from __future__ import annotations
      3 import inspect
----> 4 import itertools
      5 import os
      6 import warnings

File ~\.conda\envs\sediment\lib\site-packages\napari\layers\labels\labels.py:286, in Labels.__init__(self=<Labels layer 'mask'>, data=<class 'numpy.ndarray'> (2, 0, 1312) uint8, num_colors=50, features=None, properties=None, color=None, seed=0.5, name='mask', metadata=None, scale=None, translate=None, rotate=None, shear=None, affine=None, opacity=0.7, blending='translucent', rendering='iso_categorical', depiction='volume', visible=True, multiscale=None, cache=True, plane=None, experimental_clipping_planes=None)
    283 data = self._ensure_int_labels(data)
    284 self._color_lookup_func = None
--> 286 super().__init__(
        data = <class 'numpy.ndarray'> (2, 0, 1312) uint8
        self._random_colormap = Colormap(colors=<class 'numpy.ndarray'> (51, 4) float32, name='label_colormap', interpolation=<ColormapInterpolationMode.ZERO: 'zero'>, controls=<class 'numpy.ndarray'> (52,) float32)
        self = <Labels layer 'mask' at 0x1b04a9fb6a0>
        rendering = 'iso_categorical'
        depiction = 'volume'
        name = 'mask'
        metadata = None
        scale = None
        translate = None
        rotate = None
        shear = None
        affine = None
        opacity = 0.7
        blending = 'translucent'
        visible = True
        multiscale = None
        cache = True
        plane = None
        experimental_clipping_planes = None
    287     data,
    288     rgb=False,
    289     colormap=self._random_colormap,
    290     contrast_limits=[0.0, 1.0],
    291     interpolation2d='nearest',
    292     interpolation3d='nearest',
    293     rendering=rendering,
    294     depiction=depiction,
    295     iso_threshold=0,
    296     name=name,
    297     metadata=metadata,
    298     scale=scale,
    299     translate=translate,
    300     rotate=rotate,
    301     shear=shear,
    302     affine=affine,
    303     opacity=opacity,
    304     blending=blending,
    305     visible=visible,
    306     multiscale=multiscale,
    307     cache=cache,
    308     plane=plane,
    309     experimental_clipping_planes=experimental_clipping_planes,
    310 )
    312 self.events.add(
    313     preserve_labels=Event,
    314     show_selected_label=Event,
   (...)
    325     labels_update=Event,
    326 )
    328 self._feature_table = _FeatureTable.from_layer(
    329     features=features, properties=properties
    330 )

File ~\.conda\envs\sediment\lib\site-packages\napari\utils\migrations.py:59, in rename_argument.<locals>._wrapper.<locals>._update_from_dict(*args=(<Labels layer 'mask'>, <class 'numpy.ndarray'> (2, 0, 1312) uint8), **kwargs={'affine': None, 'blending': 'translucent', 'cache': True, 'colormap': Colormap(colors=<class 'numpy.ndarray'> (51, 4) ..., controls=<class 'numpy.ndarray'> (52,) float32), 'contrast_limits': [0.0, 1.0], 'depiction': 'volume', 'experimental_clipping_planes': None, 'interpolation2d': 'nearest', 'interpolation3d': 'nearest', 'iso_threshold': 0, ...})
     57     kwargs = kwargs.copy()
     58     kwargs[to_name] = kwargs.pop(from_name)
---> 59 return func(*args, **kwargs)
        func = <function _ImageBase.__init__ at 0x000001B0383E7790>
        kwargs = {'rgb': False, 'colormap': Colormap(colors=<class 'numpy.ndarray'> (51, 4) float32, name='label_colormap', interpolation=<ColormapInterpolationMode.ZERO: 'zero'>, controls=<class 'numpy.ndarray'> (52,) float32), 'contrast_limits': [0.0, 1.0], 'interpolation2d': 'nearest', 'interpolation3d': 'nearest', 'rendering': 'iso_categorical', 'depiction': 'volume', 'iso_threshold': 0, 'name': 'mask', 'metadata': None, 'scale': None, 'translate': None, 'rotate': None, 'shear': None, 'affine': None, 'opacity': 0.7, 'blending': 'translucent', 'visible': True, 'multiscale': None, 'cache': True, 'plane': None, 'experimental_clipping_planes': None}
        args = (<Labels layer 'mask' at 0x1b04a9fb6a0>, <class 'numpy.ndarray'> (2, 0, 1312) uint8)

File ~\.conda\envs\sediment\lib\site-packages\napari\layers\image\image.py:399, in _ImageBase.__init__(self=<Labels layer 'mask'>, data=<class 'numpy.ndarray'> (2, 0, 1312) uint8, rgb=False, colormap=Colormap(colors=<class 'numpy.ndarray'> (51, 4) ..., controls=<class 'numpy.ndarray'> (52,) float32), contrast_limits=[0.0, 1.0], gamma=1, interpolation2d='nearest', interpolation3d='nearest', rendering='iso_categorical', iso_threshold=0, attenuation=0.05, name='mask', metadata=None, scale=None, translate=None, rotate=None, shear=None, affine=None, opacity=0.7, blending='translucent', visible=True, multiscale=False, cache=True, depiction='volume', plane=None, experimental_clipping_planes=None, custom_interpolation_kernel_2d=None)
    396 self.custom_interpolation_kernel_2d = custom_interpolation_kernel_2d
    398 # Trigger generation of view slice and thumbnail
--> 399 self.refresh()
        self = <Labels layer 'mask' at 0x1b04a9fb6a0>

File ~\.conda\envs\sediment\lib\site-packages\napari\layers\base\base.py:1266, in Layer.refresh(self=<Labels layer 'mask'>, event=None)
   1264 self.set_view_slice()
   1265 self.events.set_data()
-> 1266 self._update_thumbnail()
        self = <Labels layer 'mask' at 0x1b04a9fb6a0>
   1267 self._set_highlight(force=True)

File ~\.conda\envs\sediment\lib\site-packages\napari\layers\image\image.py:953, in _ImageBase._update_thumbnail(self=<Labels layer 'mask'>)
    951         colormapped = np.concatenate([downsampled, alpha], axis=2)
    952 else:
--> 953     downsampled = ndi.zoom(
        ndi = <module 'scipy.ndimage' from 'C:\\Users\\pzahajska\\.conda\\envs\\sediment\\lib\\site-packages\\scipy\\ndimage\\__init__.py'>
        image = <class 'numpy.ndarray'> (0, 1312) float32
        zoom_factor = (inf, 0.024390243902439025)
    954         image, zoom_factor, prefilter=False, order=0
    955     )
    956     low, high = self.contrast_limits
    957     downsampled = np.clip(downsampled, low, high)

File ~\.conda\envs\sediment\lib\site-packages\scipy\ndimage\_interpolation.py:821, in zoom(input=<class 'numpy.ndarray'> (0, 1312) float32, zoom=[inf, 0.024390243902439025], output=None, order=0, mode='constant', cval=0.0, prefilter=False, grid_mode=False)
    818     raise RuntimeError('input and output rank must be > 0')
    819 zoom = _ni_support._normalize_sequence(zoom, input.ndim)
    820 output_shape = tuple(
--> 821         [int(round(ii * jj)) for ii, jj in zip(input.shape, zoom)])
        input = <class 'numpy.ndarray'> (0, 1312) float32
        zoom = [inf, 0.024390243902439025]
    822 complex_output = numpy.iscomplexobj(input)
    823 output = _ni_support._get_output(output, input, shape=output_shape,
    824                                  complex_output=complex_output)

File ~\.conda\envs\sediment\lib\site-packages\scipy\ndimage\_interpolation.py:821, in <listcomp>(.0=<zip object>)
    818     raise RuntimeError('input and output rank must be > 0')
    819 zoom = _ni_support._normalize_sequence(zoom, input.ndim)
    820 output_shape = tuple(
--> 821         [int(round(ii * jj)) for ii, jj in zip(input.shape, zoom)])
        ii, jj = (0, inf)
        ii = 0
        jj = inf
    822 complex_output = numpy.iscomplexobj(input)
    823 output = _ni_support._get_output(output, input, shape=output_shape,
    824                                  complex_output=complex_output)

ValueError: cannot convert float NaN to integer

**Comment by Epta13** [comment]
Today, I made sure that eveything from the sediment plugin is saved. I can see the zarr file, mask file (eventhough the file is just a black tiff), but when I try to load the project in the HyperAnalysis plugin, it claims that there is no .zarr existing:

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
File ~\.conda\envs\sediment\lib\site-packages\napari_sediment\hyperanalysis_widget.py:226, in HyperAnalysisWidget.import_project(self=<napari_sediment.hyperanalysis_widget.HyperAnalysisWidget object>)
    223 if self.export_folder is None:
    224     self._on_click_select_export_folder()
--> 226 self.params = load_project_params(folder=self.export_folder)
        self.params = Param(project_path='F:/HSI/Bremen/napari-cores/SO130-289KL_0_2-1_2m', file_path='F:/HSI/Bremen/Arabiansea_done/SO130-289KL_0.2-1.2m_240206-103222/capture/SO130-289KL_0.2-1.2m_240206-103222.hdr', white_path='//specimstorage02.giub.unibe.ch/specim02/Guests/ArabianSea/WR/SO130-289KL_9.2-10.2m_WR_240206-154205/capture/WHITEREF_SO130-289KL_9.2-10.2m_WR_240206-154205.hdr', dark_for_im_path='F:/HSI/Bremen/Arabiansea_done/SO130-289KL_0.2-1.2m_240206-103222/capture/DARKREF_SO130-289KL_0.2-1.2m_240206-103222.hdr', dark_for_white_path='//specimstorage02.giub.unibe.ch/specim02/Guests/ArabianSea/WR/SO130-289KL_9.2-10.2m_WR_240206-154205/capture/DARKREF_SO130-289KL_9.2-10.2m_WR_240206-154205.hdr', main_roi=[[694.6018205721907, 211.8859720664749, 12635.551733385542, 199.7889675969264, 12630.936458614364, 624.9625882188811, 694.8007199335298, 624.9625882188811]], rois=[[694.2404155777458, 420.0, 12630.888441896494, 420.0, 12630.888441896494, 440.0, 694.2404155777458, 440.0]], scale=1.0, location='No location', rgb=[640, 545, 460])
        self.export_folder = WindowsPath('F:/HSI/Bremen/napari-cores/SO130-289KL_0_2-1_2m/corrected.zarr')
        self = <napari_sediment.hyperanalysis_widget.HyperAnalysisWidget object at 0x0000023A7FEC6550>
    228 self.imhdr_path = Path(self.params.file_path)
    229 self.white_file_path = Path(self.params.white_path)

File ~\.conda\envs\sediment\lib\site-packages\napari_sediment\io.py:58, in load_project_params(folder=WindowsPath('F:/HSI/Bremen/napari-cores/SO130-289KL_0_2-1_2m/corrected.zarr'))
     56 folder = Path(folder)
     57 params = Param(project_path=folder)
---> 58 params = load_params_yml(params)
        params = Param(project_path=WindowsPath('F:/HSI/Bremen/napari-cores/SO130-289KL_0_2-1_2m/corrected.zarr'), file_path=None, white_path=None, dark_for_im_path=None, dark_for_white_path=None, main_roi=[], rois=[], scale=1, location='', rgb=[640, 545, 460])
     60 return params

File ~\.conda\envs\sediment\lib\site-packages\napari_sediment\io.py:44, in load_params_yml(params=Param(project_path=WindowsPath('F:/HSI/Bremen/na...is=[], scale=1, location='', rgb=[640, 545, 460]), file_name='Parameters.yml')
     41 def load_params_yml(params, file_name='Parameters.yml'):
     43     if not Path(params.project_path).joinpath(file_name).exists():
---> 44         raise FileNotFoundError(f"Project {params.project_path} does not exist")
     46     with open(params.project_path.joinpath(file_name)) as file:
     47         documents = yaml.full_load(file)

FileNotFoundError: Project F:\HSI\Bremen\napari-cores\SO130-289KL_0_2-1_2m\corrected.zarr does not exist

**Comment by Epta13** [comment]
If I select only the folder in which the .zarr folder is, it loads the mask, but still not the data.

**Comment by Epta13** [comment]
Select project folder must be the path to the parent folder, not pointing to the corrected.zarr. e.g. F:/HSI/Bremen/U-channel/Napari/Cariaco_slides, and not F:/HSI/Bremen/U-channel/Napari/Cariaco_slides/corrected.zarr.

This needs to be well described in the manual or somehow secured in the code.

Also, then it loads only the mast and not the data. For loading the data, one must "Select all" bands, otherwise no RGB or imcube is loaded automatically. - Could this be done: with the load project, RGB and imcube layes would open up automatickally?

**Comment by guiwitz** [comment]
As here we re-load the zarr file, it should not be a problem to import by default all channels. This is now the new behaviour as by https://github.com/guiwitz/napari-sediment/commit/a3b6f4241cafe620b576ddafb974daaa81c7ee1a
